all: file_reader.c file_reader1.c server.c info.c
	gcc file_reader.c -o file_reader
	gcc file_reader1.c -o file_reader1
	gcc server.c -o server
	gcc info.c -o info

clean:
	rm -f file_reader file_reader1 server info
